version: "3"
services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4:6.20
    container_name: pgadmin4
    restart: "no"
    ports:
      - "5480:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: chris@kpcard.co.kr
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin
    networks:
      - network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - network

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres-exporter
    ports:
      - 9187:9187
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:password@postgres:5432/postgres?sslmode=disable"
    networks:
      - network

volumes:
  data:
  pgadmin:


networks:
  network:
    driver: bridge
